### ISSUE TITLE
Broken Jenkins icons

### ISSUE THREAD

**Issue by cpt1gl0** [jenkinsci/gitlab-branch-source-plugin#185]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.343
OS: Linux - 5.13.19-6-pve
---
accelerated-build-now-plugin:1.0.1
ace-editor:1.1
analysis-model-api:10.9.4
ansicolor:1.0.1
ant:1.13
antisamy-markup-formatter:2.7
apache-httpcomponents-client-4-api:4.5.13-1.0
authentication-tokens:1.4
badge:1.9.1
bootstrap4-api:4.6.0-3
bootstrap5-api:5.1.3-6
bouncycastle-api:2.25
branch-api:2.1044.v2c007e51b_87f
build-monitor-plugin:1.13+build.202204111503
caffeine-api:2.9.2-29.v717aac953ff3
checks-api:1.7.2
cloudbees-disk-usage-simple:0.10
cloudbees-folder:6.714.v79e858ef76a_2
cobertura:1.17
code-coverage-api:2.0.4
command-launcher:1.6
conditional-buildstep:1.4.2
copyartifact:1.46.3
credentials:1112.vc87b_7a_3597f6
credentials-binding:1.27.1
dashboard-view:2.426.vb_93dcdb_b_0eb_0
data-tables-api:1.11.4-4
display-url-api:2.3.6
docker-commons:1.19
docker-java-api:3.1.5.2
docker-plugin:1.2.7
docker-workflow:1.28
doxygen:0.18
durable-task:495.v29cd95ec10f2
echarts-api:5.3.0-2
email-ext:2.87
embeddable-build-status:2.0.3
extended-read-permission:3.2
external-monitor-job:191.v363d0d1efdf8
favorite:2.4.1
font-awesome-api:6.0.0-1
forensics-api:1.12.0
git:4.11.0
git-client:3.11.0
git-server:1.10
github:1.34.3
github-api:1.301-378.v9807bd746da5
github-branch-source:1598.v91207e9f9b_4a_
gitlab-api:1.0.6
gitlab-branch-source:1.5.9
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-1.0
htmlpublisher:1.29
jackson2-api:2.13.2-260.v43d711474c77
jacoco:3.3.1
javadoc:217.v905b_86277a_2a_
javax-activation-api:1.2.0-2
javax-mail-api:1.6.2-5
jaxb:2.3.0.1
jdk-tool:1.5
jenkins-design-language:1.25.3
jira:3.7.1
jjwt-api:0.11.2-9.c8b45b8bb173
jnr-posix-api:3.1.7-3
jquery:1.12.4-1
jquery-detached:1.2.1
jquery3-api:3.6.0-2
jsch:0.1.55.2
junit:1.58
ldap:2.8
ldapemail:0.8
lockable-resources:2.14
mailer:408.vd726a_1130320
mapdb-api:1.0.9.0
matrix-auth:3.1
matrix-project:758.v7a_ea_491852f3
maven-plugin:3.18
mercurial:2.16
metrics:4.1.6.1
momentjs:1.1.1
naginator:1.18.1
nested-view:1.24
okhttp-api:4.9.3-105.vb96869f8ac3a
pam-auth:1.7
parameterized-trigger:2.44
pipeline-build-step:2.17
pipeline-graph-analysis:188.v3a01e7973f2c
pipeline-input-step:447.v95e5a_6e3502a_
pipeline-milestone-step:100.v60a_03cd446e1
pipeline-model-api:2.2075.vce74e77b_ce40
pipeline-model-definition:2.2075.vce74e77b_ce40
pipeline-model-extensions:2.2075.vce74e77b_ce40
pipeline-rest-api:2.23
pipeline-stage-step:291.vf0a8a7aeeb50
pipeline-stage-tags-metadata:2.2075.vce74e77b_ce40
pipeline-stage-view:2.23
pipeline-utility-steps:2.12.0
plain-credentials:1.8
plugin-util-api:2.16.0
popper-api:1.16.1-2
popper2-api:2.11.4-1
prism-api:1.26.0-2
prometheus:2.0.11
pubsub-light:1.16
pwauth:0.4
robot:3.1.0
run-condition:1.5
scm-api:595.vd5a_df5eb_0e39
script-security:1145.vb_cf6cf6ed960
sidebar-link:2.1.0
snakeyaml-api:1.29.1
sse-gateway:1.25
ssh-agent:1.24.1
ssh-credentials:1.19
ssh-slaves:1.806.v2253cedd3295
sshd:3.228.v4c9f9e652c86
structs:308.v852b473a2b8c
test-results-analyzer:0.3.5
theme-manager:1.2
token-macro:285.vff7645a_56ff0
trilead-api:1.57.v6e90e07157e1
variant:1.4
view-job-filters:2.3
warnings-ng:9.11.1
windows-slaves:1.8
workflow-aggregator:2.7
workflow-api:1143.v2d42f1e9dea_5
workflow-basic-steps:941.vdfe1b_a_132c64
workflow-cps:2686.v7c37e0578401
workflow-cps-global-lib:566.vd0a_a_3334a_555
workflow-durable-task-step:1128.v8c259d125340
workflow-job:1174.vdcb_d054cf74a_
workflow-multibranch:711.vdfef37cda_816
workflow-scm-step:2.13
workflow-step-api:622.vb_8e7c15b_c95a_
workflow-support:817.v58126df57338
xvfb:1.2
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 18.04.6 LTS (Bionic Beaver)

### Reproduction steps

1. Go to any GitLab branch source Multibranch Pipeline job on Jenkins web page.
2. Check for broken Gitlab branch source icons in left page area. On branch page branch icon is broken, while on project page project icon is broken. Possibly there are also other broken icons.

### Expected Results

Icons should be shown.

### Actual Results

Links to icons are broken and can not be shown.

**Comment by NotMyFault** [comment]
I've filed https://issues.jenkins.io/browse/JENKINS-68296 on Jira to track this on the ux regression dashboard.

**Comment by basil** [comment]
Caused by https://github.com/jenkinsci/jenkins/pull/6395.

**Comment by bguerin** [comment]
Has been fixed with https://github.com/jenkinsci/workflow-multibranch-plugin/pull/154 and https://github.com/jenkinsci/branch-api-plugin/pull/290

**Comment by cpt1gl0** [comment]
@bguerin Are you sure this fixed it? From the history of the mentioned PRs it can be seen that they were already merged to master on January 10.

**Comment by bguerin** [comment]
Yes but https://github.com/jenkinsci/branch-api-plugin/releases/tag/2.1044.v2c007e51b_87f released 25 days ago, and I got the update in Jenkins only yesterday

**Comment by NotMyFault** [comment]
> Has been fixed with [jenkinsci/workflow-multibranch-plugin#154](https://github.com/jenkinsci/workflow-multibranch-plugin/pull/154) and [jenkinsci/branch-api-plugin#290](https://github.com/jenkinsci/branch-api-plugin/pull/290)

The issue is not yet fixed and caused by a much more recent PR, as basil stated, and has nothing to do with the icon path removal that happened last year you mentioned the relevant update PRs for.

**Comment by bguerin** [comment]
Ok ...

But since yesterday, I do not see icons on folders and repositories, and since yesterday updates, I do

**Comment by basil** [comment]
Hello @cpt1gl0, kindly file a Jira ticket with the component set to `core` and labels set to `regression` and `ux`, along with steps to reproduce the problem from scratch (including installing Jenkins and plugins, along with version numbers), expected results, and actual results (before and after screenshots are helpful). If possible, identifying the first core release and/or commit where the regression occurred would be helpful. There is currently a large list of UX regressions, and this will need to be triaged and prioritized alongside the others.

**Comment by basil** [comment]
Great, thank you!
